# Generated by Django 5.1.4 on 2024-12-19 06:29

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_userinfo_password_check_alter_userinfo_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.contrib.auth.password_validation.MinimumLengthValidator,
                    django.contrib.auth.password_validation.NumericPasswordValidator,
                ],
            ),
        ),
    ]
