# Generated by Django 5.1.4 on 2024-12-19 06:41

import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_userinfo_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(
                max_length=150, validators=[user.validators.CustomPasswordValidator]
            ),
        ),
    ]
