# Generated by Django 5.1.4 on 2024-12-19 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_userinfo_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(regex="^[a-zA-Z][0-9]{8,}$")
                ],
            ),
        ),
    ]
